# Generated by Django 6.0.1 on 2026-01-11 17:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('borrower', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('compliance_score', models.IntegerField(default=100)),
                ('risk_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Covenant',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Financial', 'Financial'), ('Reporting', 'Reporting'), ('Affirmative', 'Affirmative'), ('Negative', 'Negative')], max_length=20)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Compliant', 'Compliant'), ('At Risk', 'At Risk'), ('Breached', 'Breached'), ('Upcoming', 'Upcoming'), ('Waived', 'Waived')], default='Upcoming', max_length=20)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('threshold', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('waiver_reason', models.TextField(blank=True, null=True)),
                ('waiver_date', models.DateField(blank=True, null=True)),
                ('waiver_approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covenants', to='api.loan')),
            ],
            options={
                'db_table': 'covenants',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanDNA',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('extracted_at', models.DateField()),
                ('source_document', models.CharField(max_length=255)),
                ('confidence', models.IntegerField()),
                ('summary', models.TextField()),
                ('facility_type', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('security_type', models.CharField(max_length=255)),
                ('governing_law', models.CharField(max_length=100)),
                ('risk_factors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_dna', to='api.loan')),
            ],
            options={
                'verbose_name': 'Loan DNA',
                'verbose_name_plural': 'Loan DNAs',
                'db_table': 'loan_dna',
            },
        ),
        migrations.CreateModel(
            name='ExtractedCovenant',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('threshold', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('loan_dna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_covenants', to='api.loandna')),
            ],
            options={
                'db_table': 'extracted_covenants',
            },
        ),
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('current_value', models.CharField(max_length=100)),
                ('threshold', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_breach_date', models.CharField(blank=True, max_length=100)),
                ('probability', models.IntegerField()),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('deteriorating', 'Deteriorating')], max_length=20)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('covenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to='api.covenant')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to='api.loan')),
            ],
            options={
                'db_table': 'risk_predictions',
                'ordering': ['-probability'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Loan Created', 'Loan Created'), ('Covenant Added', 'Covenant Added'), ('Status Changed', 'Status Changed'), ('Waiver Granted', 'Waiver Granted'), ('Payment Received', 'Payment Received'), ('Document Uploaded', 'Document Uploaded'), ('Risk Alert', 'Risk Alert'), ('Amendment Made', 'Amendment Made')], max_length=50)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='api.loan')),
                ('related_covenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='api.covenant')),
            ],
            options={
                'db_table': 'timeline_events',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='loan_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='api.loan')),
            ],
            options={
                'db_table': 'uploaded_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
