import { Loan, LoanStatus, ComplianceStatus, TimelineEventType } from './types';

export const MOCK_LOANS: Loan[] = [
  {
    id: 'ln_001',
    borrower: 'Acme Corp Industrial',
    amount: 15000000,
    currency: 'USD',
    interestRate: 5.5,
    startDate: '2023-01-15',
    maturityDate: '2028-01-15',
    status: LoanStatus.Active,
    complianceScore: 92,
    uploadedDocuments: ['loan_agreement_acme.pdf'],
    loanDNA: {
      extractedAt: '2023-01-16',
      sourceDocument: 'loan_agreement_acme.pdf',
      confidence: 94,
      keyTerms: {
        facilityType: 'Term Loan B',
        purpose: 'Working Capital & Expansion',
        securityType: 'Senior Secured',
        governingLaw: 'New York',
      },
      extractedCovenants: [
        { title: 'Leverage Ratio', type: 'Financial', threshold: '< 4.0x', frequency: 'Quarterly', description: 'Total Net Debt to EBITDA' },
        { title: 'Interest Coverage', type: 'Financial', threshold: '> 2.5x', frequency: 'Quarterly', description: 'EBITDA to Interest Expense' },
        { title: 'Quarterly Financials', type: 'Reporting', threshold: 'Within 45 days', frequency: 'Quarterly', description: 'Unaudited financial statements' },
      ],
      riskFactors: [
        'High leverage in cyclical industry',
        'Concentration risk in single market segment',
        'Upcoming capex requirements may strain cash flow',
      ],
      summary: 'Senior secured term loan for industrial manufacturing company with standard financial covenants. Moderate risk profile with tight leverage headroom.',
    },
    riskPredictions: [
      {
        covenantId: 'cov_2',
        covenantTitle: 'Leverage Ratio',
        currentValue: '3.9x',
        threshold: '< 4.0x',
        predictedBreachDate: '2024-06-30',
        probability: 72,
        trend: 'deteriorating',
        explanation: 'Based on declining EBITDA trend (-8% QoQ) and stable debt levels, leverage ratio is projected to exceed 4.0x threshold within 2 quarters. Recommend proactive engagement with borrower.',
      },
      {
        covenantId: 'cov_3',
        covenantTitle: 'Interest Coverage',
        currentValue: '4.2x',
        threshold: '> 2.5x',
        predictedBreachDate: '',
        probability: 15,
        trend: 'stable',
        explanation: 'Interest coverage remains healthy with significant buffer. Low breach probability unless significant EBITDA deterioration occurs.',
      },
    ],
    timelineEvents: [
      {
        id: 'evt_001',
        type: TimelineEventType.LoanCreated,
        date: '2023-01-15',
        title: 'Loan Facility Established',
        description: 'USD 15M Term Loan B facility established with Acme Corp Industrial. 5-year tenor with quarterly amortization.',
      },
      {
        id: 'evt_002',
        type: TimelineEventType.DocumentUploaded,
        date: '2023-01-16',
        title: 'Loan Agreement Uploaded',
        description: 'Original loan agreement document uploaded and processed. AI extracted 3 covenants with 94% confidence.',
      },
      {
        id: 'evt_003',
        type: TimelineEventType.CovenantAdded,
        date: '2023-01-16',
        title: 'Covenants Configured',
        description: 'Financial covenants (Leverage Ratio, Interest Coverage) and Reporting covenant (Quarterly Financials) added to monitoring.',
      },
      {
        id: 'evt_004',
        type: TimelineEventType.StatusChanged,
        date: '2023-09-30',
        title: 'Leverage Ratio Status Changed',
        description: 'Leverage Ratio covenant status changed from Compliant to At Risk. Current value 3.9x approaching threshold of 4.0x.',
        relatedCovenantId: 'cov_2',
      },
      {
        id: 'evt_005',
        type: TimelineEventType.RiskAlert,
        date: '2023-10-15',
        title: 'Predictive Alert: Potential Breach',
        description: 'AI analysis indicates 72% probability of Leverage Ratio breach within 2 quarters based on EBITDA trend deterioration.',
        relatedCovenantId: 'cov_2',
      },
    ],
    covenants: [
      {
        id: 'cov_1',
        title: 'Quarterly Financials',
        type: 'Reporting',
        dueDate: '2024-03-31',
        status: ComplianceStatus.Compliant,
        description: 'Submission of unaudited quarterly financial statements within 45 days of quarter end.',
        frequency: 'Quarterly',
      },
      {
        id: 'cov_2',
        title: 'Leverage Ratio',
        type: 'Financial',
        dueDate: '2024-03-31',
        status: ComplianceStatus.AtRisk,
        value: '3.9x',
        threshold: '< 4.0x',
        description: 'Total Net Debt to EBITDA must not exceed 4.0x.',
        frequency: 'Quarterly',
      },
      {
        id: 'cov_3',
        title: 'Interest Coverage',
        type: 'Financial',
        dueDate: '2024-06-30',
        status: ComplianceStatus.Upcoming,
        threshold: '> 2.5x',
        description: 'EBITDA to Interest Expense ratio must be maintained above 2.5x.',
        frequency: 'Quarterly',
      },
    ],
  },
  {
    id: 'ln_002',
    borrower: 'Helios Energy Ltd',
    amount: 45000000,
    currency: 'USD',
    interestRate: 6.2,
    startDate: '2022-06-01',
    maturityDate: '2027-06-01',
    status: LoanStatus.Active,
    complianceScore: 78,
    uploadedDocuments: ['helios_facility_agreement.pdf', 'amendment_1.pdf'],
    loanDNA: {
      extractedAt: '2022-06-02',
      sourceDocument: 'helios_facility_agreement.pdf',
      confidence: 91,
      keyTerms: {
        facilityType: 'Revolving Credit Facility',
        purpose: 'Project Finance - Solar Installation',
        securityType: 'Asset-Backed',
        governingLaw: 'Delaware',
      },
      extractedCovenants: [
        { title: 'Debt Service Coverage', type: 'Financial', threshold: '> 1.25x', frequency: 'Quarterly', description: 'DSCR on rolling 12-month basis' },
        { title: 'Annual Audit', type: 'Reporting', threshold: 'Within 90 days', frequency: 'Annual', description: 'Audited financials by Big 4 firm' },
      ],
      riskFactors: [
        'Project execution risk on new installations',
        'Regulatory dependency on renewable energy incentives',
        'Weather-related revenue variability',
      ],
      summary: 'Asset-backed revolving facility for renewable energy company. Higher risk profile due to project execution dependencies and regulatory exposure.',
    },
    riskPredictions: [
      {
        covenantId: 'cov_5',
        covenantTitle: 'Debt Service Coverage',
        currentValue: '1.1x',
        threshold: '> 1.25x',
        predictedBreachDate: '2024-01-15',
        probability: 95,
        trend: 'deteriorating',
        explanation: 'DSCR already below threshold at 1.1x. Immediate breach confirmed. Recommend initiating waiver discussion or amendment process.',
      },
    ],
    timelineEvents: [
      {
        id: 'evt_010',
        type: TimelineEventType.LoanCreated,
        date: '2022-06-01',
        title: 'Revolving Facility Established',
        description: 'USD 45M Revolving Credit Facility established for Helios Energy solar project financing.',
      },
      {
        id: 'evt_011',
        type: TimelineEventType.StatusChanged,
        date: '2023-06-30',
        title: 'DSCR Covenant Breached',
        description: 'Debt Service Coverage Ratio fell to 1.1x, below the required 1.25x threshold. Breach notification sent to borrower.',
        relatedCovenantId: 'cov_5',
      },
      {
        id: 'evt_012',
        type: TimelineEventType.AmendmentMade,
        date: '2023-08-15',
        title: 'Amendment 1 Executed',
        description: 'First amendment executed providing temporary DSCR covenant relief. New threshold of 1.1x effective through Q4 2023.',
      },
      {
        id: 'evt_013',
        type: TimelineEventType.RiskAlert,
        date: '2023-11-01',
        title: 'Amendment Expiry Warning',
        description: 'Temporary covenant relief expires in 60 days. Current DSCR of 1.1x will breach original 1.25x threshold.',
        relatedCovenantId: 'cov_5',
      },
    ],
    covenants: [
      {
        id: 'cov_4',
        title: 'Annual Audit',
        type: 'Reporting',
        dueDate: '2023-12-31',
        status: ComplianceStatus.Compliant,
        description: 'Audited annual financials by KPMG or equivalent.',
        frequency: 'Annual',
      },
      {
        id: 'cov_5',
        title: 'Debt Service Coverage',
        type: 'Financial',
        dueDate: '2024-03-31',
        status: ComplianceStatus.Breached,
        value: '1.1x',
        threshold: '> 1.25x',
        description: 'DSCR must be greater than 1.25x calculated on a rolling 12-month basis.',
        frequency: 'Quarterly',
      },
    ],
  },
  {
    id: 'ln_003',
    borrower: 'Omni Retail Group',
    amount: 8500000,
    currency: 'USD',
    interestRate: 4.8,
    startDate: '2023-09-01',
    maturityDate: '2026-09-01',
    status: LoanStatus.Pending,
    complianceScore: 100,
    uploadedDocuments: [],
    timelineEvents: [
      {
        id: 'evt_020',
        type: TimelineEventType.LoanCreated,
        date: '2023-09-01',
        title: 'Loan Application Received',
        description: 'USD 8.5M term loan application received from Omni Retail Group. Pending document upload and covenant configuration.',
      },
    ],
    covenants: [],
  },
  {
    id: 'ln_004',
    borrower: 'TechVenture Solutions',
    amount: 25000000,
    currency: 'USD',
    interestRate: 7.25,
    startDate: '2023-03-15',
    maturityDate: '2028-03-15',
    status: LoanStatus.Active,
    complianceScore: 88,
    uploadedDocuments: ['techventure_credit_agreement.pdf'],
    loanDNA: {
      extractedAt: '2023-03-16',
      sourceDocument: 'techventure_credit_agreement.pdf',
      confidence: 92,
      keyTerms: {
        facilityType: 'Senior Term Loan',
        purpose: 'Acquisition Financing',
        securityType: 'Senior Secured - First Lien',
        governingLaw: 'New York',
      },
      extractedCovenants: [
        { title: 'Total Leverage Ratio', type: 'Financial', threshold: '< 5.0x', frequency: 'Quarterly', description: 'Total Debt to EBITDA' },
        { title: 'Fixed Charge Coverage', type: 'Financial', threshold: '> 1.1x', frequency: 'Quarterly', description: 'EBITDA minus CapEx to Fixed Charges' },
        { title: 'Monthly Revenue Report', type: 'Reporting', threshold: 'Within 30 days', frequency: 'Monthly', description: 'Monthly revenue and ARR metrics' },
      ],
      riskFactors: [
        'High growth tech company with negative cash flow',
        'Customer concentration in top 5 accounts',
        'Integration risk from recent acquisition',
      ],
      summary: 'Senior secured acquisition financing for SaaS company. Elevated risk due to growth-stage profile but strong ARR trajectory provides comfort.',
    },
    riskPredictions: [
      {
        covenantId: 'cov_tv_1',
        covenantTitle: 'Total Leverage Ratio',
        currentValue: '4.6x',
        threshold: '< 5.0x',
        predictedBreachDate: '2024-09-30',
        probability: 45,
        trend: 'stable',
        explanation: 'Leverage elevated but stable. EBITDA growth expected to reduce ratio over next 2 quarters. Monitor closely.',
      },
    ],
    timelineEvents: [
      {
        id: 'evt_tv_001',
        type: TimelineEventType.LoanCreated,
        date: '2023-03-15',
        title: 'Acquisition Facility Closed',
        description: 'USD 25M Senior Term Loan closed to fund acquisition of CloudSync Inc. 5-year tenor with bullet maturity.',
      },
      {
        id: 'evt_tv_002',
        type: TimelineEventType.DocumentUploaded,
        date: '2023-03-16',
        title: 'Credit Agreement Processed',
        description: 'Credit agreement uploaded and analyzed. AI extracted 3 covenants with 92% confidence.',
      },
      {
        id: 'evt_tv_003',
        type: TimelineEventType.PaymentReceived,
        date: '2023-12-15',
        title: 'Q4 Interest Payment Received',
        description: 'Quarterly interest payment of $453,125 received on schedule.',
      },
    ],
    covenants: [
      {
        id: 'cov_tv_1',
        title: 'Total Leverage Ratio',
        type: 'Financial',
        dueDate: '2024-03-31',
        status: ComplianceStatus.Compliant,
        value: '4.6x',
        threshold: '< 5.0x',
        description: 'Total Debt to EBITDA must not exceed 5.0x.',
        frequency: 'Quarterly',
      },
      {
        id: 'cov_tv_2',
        title: 'Fixed Charge Coverage',
        type: 'Financial',
        dueDate: '2024-03-31',
        status: ComplianceStatus.Compliant,
        value: '1.3x',
        threshold: '> 1.1x',
        description: 'EBITDA minus CapEx to Fixed Charges ratio must exceed 1.1x.',
        frequency: 'Quarterly',
      },
      {
        id: 'cov_tv_3',
        title: 'Monthly Revenue Report',
        type: 'Reporting',
        dueDate: '2024-02-28',
        status: ComplianceStatus.Compliant,
        description: 'Monthly submission of revenue metrics and ARR dashboard.',
        frequency: 'Monthly',
      },
    ],
  },
  {
    id: 'ln_005',
    borrower: 'Pacific Healthcare Systems',
    amount: 75000000,
    currency: 'USD',
    interestRate: 5.0,
    startDate: '2022-11-01',
    maturityDate: '2029-11-01',
    status: LoanStatus.Active,
    complianceScore: 96,
    uploadedDocuments: ['pacific_healthcare_facility.pdf', 'compliance_certificate_q3.pdf'],
    loanDNA: {
      extractedAt: '2022-11-02',
      sourceDocument: 'pacific_healthcare_facility.pdf',
      confidence: 97,
      keyTerms: {
        facilityType: 'Syndicated Term Loan',
        purpose: 'Hospital Expansion & Equipment',
        securityType: 'Senior Secured - Real Estate',
        governingLaw: 'California',
      },
      extractedCovenants: [
        { title: 'Debt to Capitalization', type: 'Financial', threshold: '< 60%', frequency: 'Quarterly', description: 'Total Debt to Total Capitalization' },
        { title: 'Days Cash on Hand', type: 'Financial', threshold: '> 60 days', frequency: 'Quarterly', description: 'Unrestricted cash divided by daily operating expenses' },
        { title: 'Annual Audited Financials', type: 'Reporting', threshold: 'Within 120 days', frequency: 'Annual', description: 'Audited financials with compliance certificate' },
      ],
      riskFactors: [
        'Healthcare regulatory changes could impact reimbursement',
        'Labor cost inflation in nursing staff',
        'Capital intensive expansion program',
      ],
      summary: 'Well-structured syndicated facility for established healthcare system. Strong credit profile with real estate collateral. Low risk.',
    },
    riskPredictions: [
      {
        covenantId: 'cov_ph_1',
        covenantTitle: 'Debt to Capitalization',
        currentValue: '48%',
        threshold: '< 60%',
        predictedBreachDate: '',
        probability: 8,
        trend: 'improving',
        explanation: 'Strong deleveraging trend. Ratio improved from 52% to 48% over past year. Very low breach probability.',
      },
    ],
    timelineEvents: [
      {
        id: 'evt_ph_001',
        type: TimelineEventType.LoanCreated,
        date: '2022-11-01',
        title: 'Syndicated Facility Closed',
        description: 'USD 75M Syndicated Term Loan closed with 5 participating lenders. Lead arranger: First National Bank.',
      },
      {
        id: 'evt_ph_002',
        type: TimelineEventType.StatusChanged,
        date: '2023-06-30',
        title: 'All Covenants Compliant',
        description: 'Q2 2023 compliance certificate received. All financial covenants in compliance with healthy headroom.',
      },
      {
        id: 'evt_ph_003',
        type: TimelineEventType.PaymentReceived,
        date: '2024-01-02',
        title: 'Principal + Interest Payment',
        description: 'Scheduled principal payment of $2.5M plus interest received. Loan balance now $67.5M.',
      },
    ],
    covenants: [
      {
        id: 'cov_ph_1',
        title: 'Debt to Capitalization',
        type: 'Financial',
        dueDate: '2024-03-31',
        status: ComplianceStatus.Compliant,
        value: '48%',
        threshold: '< 60%',
        description: 'Total Debt to Total Capitalization ratio must remain below 60%.',
        frequency: 'Quarterly',
      },
      {
        id: 'cov_ph_2',
        title: 'Days Cash on Hand',
        type: 'Financial',
        dueDate: '2024-03-31',
        status: ComplianceStatus.Compliant,
        value: '85 days',
        threshold: '> 60 days',
        description: 'Must maintain minimum 60 days cash on hand.',
        frequency: 'Quarterly',
      },
      {
        id: 'cov_ph_3',
        title: 'Annual Audited Financials',
        type: 'Reporting',
        dueDate: '2024-04-30',
        status: ComplianceStatus.Upcoming,
        description: 'Submission of audited annual financials within 120 days of fiscal year end.',
        frequency: 'Annual',
      },
    ],
  },
  {
    id: 'ln_006',
    borrower: 'Metro Logistics Inc',
    amount: 12000000,
    currency: 'EUR',
    interestRate: 4.5,
    startDate: '2023-07-01',
    maturityDate: '2026-07-01',
    status: LoanStatus.Active,
    complianceScore: 65,
    uploadedDocuments: ['metro_logistics_agreement.pdf'],
    loanDNA: {
      extractedAt: '2023-07-02',
      sourceDocument: 'metro_logistics_agreement.pdf',
      confidence: 89,
      keyTerms: {
        facilityType: 'Working Capital Facility',
        purpose: 'Fleet Expansion & Operations',
        securityType: 'Asset-Backed - Fleet Vehicles',
        governingLaw: 'English Law',
      },
      extractedCovenants: [
        { title: 'Current Ratio', type: 'Financial', threshold: '> 1.2x', frequency: 'Quarterly', description: 'Current Assets to Current Liabilities' },
        { title: 'EBITDA Margin', type: 'Financial', threshold: '> 8%', frequency: 'Quarterly', description: 'EBITDA as percentage of Revenue' },
        { title: 'Fleet Utilization Report', type: 'Reporting', threshold: 'Within 15 days', frequency: 'Monthly', description: 'Monthly fleet utilization and maintenance report' },
      ],
      riskFactors: [
        'Fuel price volatility impacts margins',
        'Driver shortage affecting capacity',
        'Competitive pressure from new market entrants',
        'Currency exposure on cross-border operations',
      ],
      summary: 'Asset-backed working capital facility for logistics company. Elevated risk due to thin margins and operational challenges. Close monitoring required.',
    },
    riskPredictions: [
      {
        covenantId: 'cov_ml_2',
        covenantTitle: 'EBITDA Margin',
        currentValue: '7.2%',
        threshold: '> 8%',
        predictedBreachDate: '2024-03-31',
        probability: 82,
        trend: 'deteriorating',
        explanation: 'EBITDA margin has declined for 3 consecutive quarters due to fuel costs and wage inflation. High probability of breach at next test date.',
      },
      {
        covenantId: 'cov_ml_1',
        covenantTitle: 'Current Ratio',
        currentValue: '1.15x',
        threshold: '> 1.2x',
        predictedBreachDate: '2024-03-31',
        probability: 68,
        trend: 'deteriorating',
        explanation: 'Working capital under pressure. Current ratio trending down from 1.3x to 1.15x. Recommend discussing liquidity support options.',
      },
    ],
    timelineEvents: [
      {
        id: 'evt_ml_001',
        type: TimelineEventType.LoanCreated,
        date: '2023-07-01',
        title: 'Working Capital Facility Established',
        description: 'EUR 12M Working Capital Facility established for Metro Logistics fleet expansion.',
      },
      {
        id: 'evt_ml_002',
        type: TimelineEventType.StatusChanged,
        date: '2023-12-31',
        title: 'EBITDA Margin At Risk',
        description: 'Q4 results show EBITDA margin of 7.2%, below 8% threshold. Status changed to At Risk.',
        relatedCovenantId: 'cov_ml_2',
      },
      {
        id: 'evt_ml_003',
        type: TimelineEventType.RiskAlert,
        date: '2024-01-10',
        title: 'Multiple Covenant Warning',
        description: 'AI analysis indicates elevated breach probability for both EBITDA Margin (82%) and Current Ratio (68%) covenants.',
      },
    ],
    covenants: [
      {
        id: 'cov_ml_1',
        title: 'Current Ratio',
        type: 'Financial',
        dueDate: '2024-03-31',
        status: ComplianceStatus.AtRisk,
        value: '1.15x',
        threshold: '> 1.2x',
        description: 'Current Assets to Current Liabilities must exceed 1.2x.',
        frequency: 'Quarterly',
      },
      {
        id: 'cov_ml_2',
        title: 'EBITDA Margin',
        type: 'Financial',
        dueDate: '2024-03-31',
        status: ComplianceStatus.AtRisk,
        value: '7.2%',
        threshold: '> 8%',
        description: 'EBITDA as percentage of Revenue must exceed 8%.',
        frequency: 'Quarterly',
      },
      {
        id: 'cov_ml_3',
        title: 'Fleet Utilization Report',
        type: 'Reporting',
        dueDate: '2024-02-15',
        status: ComplianceStatus.Compliant,
        description: 'Monthly fleet utilization and maintenance metrics.',
        frequency: 'Monthly',
      },
    ],
  },
];

export const ANIMATION_VARIANTS = {
  container: {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.2,
      },
    },
  },
  item: {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { type: 'spring' as const, stiffness: 50, damping: 20 } },
  },
};
