import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, Download, Filter, Calendar, Home, ChevronRight, X, CheckCircle, ChevronDown } from 'lucide-react';
import { Card } from '../components/ui/Card';
import { Loan, ComplianceStatus } from '../types';

interface ReportsViewProps {
    loans: Loan[];
}

const ReportsView: React.FC<ReportsViewProps> = ({ loans }) => {
  const [generating, setGenerating] = useState<string | null>(null);
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [downloadedReport, setDownloadedReport] = useState<string>('');
  const [dateRange, setDateRange] = useState('30');
  const [showDateDropdown, setShowDateDropdown] = useState(false);
  const [filterType, setFilterType] = useState('all');
  const [showFilterDropdown, setShowFilterDropdown] = useState(false);

  const dateRangeOptions = [
    { value: '7', label: 'Last 7 Days' },
    { value: '30', label: 'Last 30 Days' },
    { value: '90', label: 'Last 90 Days' },
    { value: '365', label: 'Last Year' },
    { value: 'all', label: 'All Time' },
  ];

  const filterOptions = [
    { value: 'all', label: 'All Reports' },
    { value: 'pdf', label: 'PDF Only' },
    { value: 'csv', label: 'CSV Only' },
    { value: 'compliance', label: 'Compliance Reports' },
    { value: 'risk', label: 'Risk Reports' },
  ];

  const generateDummyReport = (reportId: string, reportType: string): string => {
    const today = new Date().toLocaleDateString();
    
    if (reportId === 'r1') {
      // Portfolio Compliance Summary
      return `PORTFOLIO COMPLIANCE SUMMARY REPORT
Generated: ${today}
Generated By: Admin User

================================================================================
EXECUTIVE SUMMARY
================================================================================

Total Active Loans: ${totalLoans}
Total Covenants Monitored: ${loans.reduce((acc, l) => acc + l.covenants.length, 0)}
Portfolio Compliance Score: ${totalLoans > 0 ? Math.round(loans.reduce((acc, l) => acc + l.complianceScore, 0) / totalLoans) : 0}%
At Risk / Breached Items: ${atRiskCount}

================================================================================
LOAN DETAILS
================================================================================

${loans.map(loan => `
LOAN: ${loan.borrower}
  Loan ID: ${loan.id}
  Amount: ${loan.currency} ${loan.amount.toLocaleString()}
  Interest Rate: ${loan.interestRate}%
  Status: ${loan.status}
  Compliance Score: ${loan.complianceScore}/100
  Covenants: ${loan.covenants.length}
  
  Covenant Status:
${loan.covenants.map(c => `    - ${c.title}: ${c.status} (Due: ${c.dueDate})`).join('\n') || '    No covenants configured'}
`).join('\n')}

================================================================================
RISK SUMMARY
================================================================================

High Risk Loans: ${loans.filter(l => l.complianceScore < 70).length}
Medium Risk Loans: ${loans.filter(l => l.complianceScore >= 70 && l.complianceScore < 85).length}
Low Risk Loans: ${loans.filter(l => l.complianceScore >= 85).length}

================================================================================
END OF REPORT
================================================================================
`;
    }
    
    if (reportId === 'r2') {
      // Risk Assessment Matrix (CSV)
      let csv = 'Loan ID,Borrower,Amount,Currency,Compliance Score,Status,At Risk Count,Breached Count,Total Covenants\n';
      loans.forEach(loan => {
        const atRisk = loan.covenants.filter(c => c.status === ComplianceStatus.AtRisk).length;
        const breached = loan.covenants.filter(c => c.status === ComplianceStatus.Breached).length;
        csv += `${loan.id},${loan.borrower},${loan.amount},${loan.currency},${loan.complianceScore},${loan.status},${atRisk},${breached},${loan.covenants.length}\n`;
      });
      return csv;
    }
    
    if (reportId === 'r3') {
      // Monthly Covenant Digest
      const now = new Date();
      const thisMonth = now.getMonth();
      const thisYear = now.getFullYear();
      
      const upcomingCovenants = loans.flatMap(loan => 
        loan.covenants.filter(c => {
          const dueDate = new Date(c.dueDate);
          return dueDate.getMonth() === thisMonth && dueDate.getFullYear() === thisYear;
        }).map(c => ({ ...c, borrower: loan.borrower, loanId: loan.id }))
      );
      
      return `MONTHLY COVENANT DIGEST
Generated: ${today}
Period: ${now.toLocaleString('default', { month: 'long', year: 'numeric' })}

================================================================================
COVENANTS DUE THIS MONTH: ${upcomingCovenants.length}
================================================================================

${upcomingCovenants.length === 0 ? 'No covenants due this month.' : upcomingCovenants.map(c => `
Covenant: ${c.title}
  Borrower: ${c.borrower}
  Type: ${c.type}
  Due Date: ${c.dueDate}
  Status: ${c.status}
  Threshold: ${c.threshold || 'N/A'}
  Current Value: ${c.value || 'Pending'}
`).join('\n')}

================================================================================
UPCOMING NEXT MONTH
================================================================================

${loans.flatMap(loan => 
  loan.covenants.filter(c => {
    const dueDate = new Date(c.dueDate);
    const nextMonth = (thisMonth + 1) % 12;
    const nextYear = thisMonth === 11 ? thisYear + 1 : thisYear;
    return dueDate.getMonth() === nextMonth && dueDate.getFullYear() === nextYear;
  }).map(c => `- ${c.title} (${loan.borrower}) - Due: ${c.dueDate}`)
).join('\n') || 'No covenants due next month.'}

================================================================================
END OF REPORT
================================================================================
`;
    }
    
    if (reportId === 'r4') {
      // Audit Trail Log (CSV)
      let csv = 'Date,Event Type,Loan,Title,Description\n';
      loans.forEach(loan => {
        (loan.timelineEvents || []).forEach(event => {
          csv += `${event.date},"${event.type}","${loan.borrower}","${event.title}","${event.description.replace(/"/g, '""')}"\n`;
        });
      });
      return csv;
    }
    
    return 'Report content not available.';
  };

  const handleDownload = (reportId: string, reportTitle: string, reportType: string) => {
    setGenerating(reportId);
    setTimeout(() => {
        // Generate the report content
        const content = generateDummyReport(reportId, reportType);
        const isCSV = reportType === 'CSV';
        const blob = new Blob([content], { type: isCSV ? 'text/csv;charset=utf-8;' : 'text/plain;charset=utf-8;' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = `${reportTitle.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.${isCSV ? 'csv' : 'txt'}`;
        link.click();
        
        setGenerating(null);
        setDownloadedReport(reportTitle);
        setShowSuccessModal(true);
    }, 2000);
  };

  const allReports = [
    { id: 'r1', title: 'Portfolio Compliance Summary', type: 'PDF', category: 'compliance', desc: 'Complete overview of all active loans and covenant statuses.' },
    { id: 'r2', title: 'Risk Assessment Matrix', type: 'CSV', category: 'risk', desc: 'Raw data export of risk scores and financial metrics.' },
    { id: 'r3', title: 'Monthly Covenant Digest', type: 'PDF', category: 'compliance', desc: 'Detailed breakdown of covenants due in the current month.' },
    { id: 'r4', title: 'Audit Trail Log', type: 'CSV', category: 'compliance', desc: 'History of all changes and compliance checks performed.' },
  ];

  // Filter reports based on selected filter
  const reports = allReports.filter(report => {
    if (filterType === 'all') return true;
    if (filterType === 'pdf') return report.type === 'PDF';
    if (filterType === 'csv') return report.type === 'CSV';
    if (filterType === 'compliance') return report.category === 'compliance';
    if (filterType === 'risk') return report.category === 'risk';
    return true;
  });

  // Generate dynamic stats based on loans
  const totalLoans = loans.length;
  const atRiskCount = loans.reduce((acc, loan) => 
    acc + loan.covenants.filter(c => c.status === ComplianceStatus.AtRisk || c.status === ComplianceStatus.Breached).length, 0);

  const getDateRangeLabel = () => {
    const option = dateRangeOptions.find(o => o.value === dateRange);
    return option ? option.label : 'Last 30 Days';
  };

  const getFilterLabel = () => {
    const option = filterOptions.find(o => o.value === filterType);
    return option ? option.label : 'All Reports';
  };

  return (
    <div className="p-4 md:p-6 lg:p-10 max-w-7xl mx-auto">
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-4">
        <div>
           <h1 className="text-2xl md:text-3xl font-bold text-white tracking-tight">Reports Center</h1>
           <p className="text-slate-400 mt-1 text-sm md:text-base">Generate and export insights for stakeholders.</p>
        </div>
        <div className="flex gap-2 md:gap-3">
             {/* Date Range Dropdown */}
             <div className="relative">
               <button 
                 onClick={() => { setShowDateDropdown(!showDateDropdown); setShowFilterDropdown(false); }}
                 className="flex items-center gap-2 px-3 md:px-4 py-2 bg-slate-900 border border-slate-700 rounded-lg text-slate-300 hover:text-white hover:border-slate-600 transition-colors text-sm"
               >
                  <Calendar className="w-4 h-4" /> 
                  <span className="hidden sm:inline">{getDateRangeLabel()}</span>
                  <span className="sm:hidden">{dateRange === 'all' ? 'All' : dateRange + 'd'}</span>
                  <ChevronDown className={`w-3 h-3 transition-transform ${showDateDropdown ? 'rotate-180' : ''}`} />
               </button>
               
               <AnimatePresence>
                 {showDateDropdown && (
                   <motion.div
                     initial={{ opacity: 0, y: -10 }}
                     animate={{ opacity: 1, y: 0 }}
                     exit={{ opacity: 0, y: -10 }}
                     className="absolute top-full mt-2 right-0 w-48 bg-slate-900 border border-slate-700 rounded-lg shadow-xl z-20 overflow-hidden"
                   >
                     {dateRangeOptions.map(option => (
                       <button
                         key={option.value}
                         onClick={() => { setDateRange(option.value); setShowDateDropdown(false); }}
                         className={`w-full text-left px-4 py-2.5 text-sm transition-colors ${
                           dateRange === option.value 
                             ? 'bg-emerald-500/10 text-emerald-400' 
                             : 'text-slate-300 hover:bg-slate-800 hover:text-white'
                         }`}
                       >
                         {option.label}
                       </button>
                     ))}
                   </motion.div>
                 )}
               </AnimatePresence>
             </div>

             {/* Filter Dropdown */}
             <div className="relative">
               <button 
                 onClick={() => { setShowFilterDropdown(!showFilterDropdown); setShowDateDropdown(false); }}
                 className="flex items-center gap-2 px-3 md:px-4 py-2 bg-slate-900 border border-slate-700 rounded-lg text-slate-300 hover:text-white hover:border-slate-600 transition-colors text-sm"
               >
                  <Filter className="w-4 h-4" /> 
                  <span className="hidden sm:inline">{getFilterLabel()}</span>
                  <ChevronDown className={`w-3 h-3 transition-transform ${showFilterDropdown ? 'rotate-180' : ''}`} />
               </button>
               
               <AnimatePresence>
                 {showFilterDropdown && (
                   <motion.div
                     initial={{ opacity: 0, y: -10 }}
                     animate={{ opacity: 1, y: 0 }}
                     exit={{ opacity: 0, y: -10 }}
                     className="absolute top-full mt-2 right-0 w-48 bg-slate-900 border border-slate-700 rounded-lg shadow-xl z-20 overflow-hidden"
                   >
                     {filterOptions.map(option => (
                       <button
                         key={option.value}
                         onClick={() => { setFilterType(option.value); setShowFilterDropdown(false); }}
                         className={`w-full text-left px-4 py-2.5 text-sm transition-colors ${
                           filterType === option.value 
                             ? 'bg-emerald-500/10 text-emerald-400' 
                             : 'text-slate-300 hover:bg-slate-800 hover:text-white'
                         }`}
                       >
                         {option.label}
                       </button>
                     ))}
                   </motion.div>
                 )}
               </AnimatePresence>
             </div>
        </div>
      </header>

      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-sm text-slate-400 mb-6">
        <Home className="w-4 h-4" />
        <ChevronRight className="w-3 h-3" />
        <span className="text-white">Reports</span>
      </div>

      {/* Stats Summary */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
        <div className="bg-slate-900 border border-slate-800 rounded-lg p-4">
          <div className="text-2xl font-bold text-white">{totalLoans}</div>
          <div className="text-xs text-slate-400">Active Loans</div>
        </div>
        <div className="bg-slate-900 border border-slate-800 rounded-lg p-4">
          <div className="text-2xl font-bold text-emerald-400">{reports.length}</div>
          <div className="text-xs text-slate-400">Available Reports</div>
        </div>
        <div className="bg-slate-900 border border-slate-800 rounded-lg p-4">
          <div className="text-2xl font-bold text-amber-400">{atRiskCount}</div>
          <div className="text-xs text-slate-400">At Risk Items</div>
        </div>
        <div className="bg-slate-900 border border-slate-800 rounded-lg p-4">
          <div className="text-2xl font-bold text-blue-400">2</div>
          <div className="text-xs text-slate-400">Recent Exports</div>
        </div>
      </div>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 md:gap-6">
        {reports.length === 0 ? (
          <div className="col-span-2 text-center py-12 bg-slate-900/50 border border-slate-800 rounded-xl">
            <Filter className="w-12 h-12 text-slate-600 mx-auto mb-3" />
            <p className="text-slate-400">No reports match your filter criteria.</p>
            <button 
              onClick={() => setFilterType('all')}
              className="mt-3 text-emerald-400 hover:underline text-sm"
            >
              Clear filters
            </button>
          </div>
        ) : (
          reports.map((report) => (
            <Card key={report.id} className="hover:border-emerald-500/30 transition-all">
                <div className="flex items-start justify-between mb-3 md:mb-4">
                    <div className="p-2 md:p-3 bg-slate-800 rounded-lg text-emerald-400">
                        <FileText className="w-5 h-5 md:w-6 md:h-6" />
                    </div>
                    <span className="px-2 py-1 text-xs font-medium bg-slate-800 text-slate-400 rounded border border-slate-700">{report.type}</span>
                </div>
                <h3 className="text-base md:text-lg font-bold text-white mb-2">{report.title}</h3>
                <p className="text-slate-400 text-xs md:text-sm mb-4 md:mb-6 min-h-[40px]">{report.desc}</p>
                
                <button 
                    onClick={() => handleDownload(report.id, report.title, report.type)}
                    disabled={!!generating}
                    className="w-full flex items-center justify-center gap-2 py-2 md:py-2.5 bg-slate-800 hover:bg-slate-700 text-white rounded-lg border border-slate-700 transition-all disabled:opacity-70 text-sm"
                >
                    {generating === report.id ? (
                        <>
                             <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                             Generating...
                        </>
                    ) : (
                        <>
                            <Download className="w-4 h-4" /> Download Report
                        </>
                    )}
                </button>
            </Card>
          ))
        )}
      </div>

      <h2 className="text-lg md:text-xl font-bold text-white mt-8 md:mt-12 mb-4 md:mb-6">Recent Exports</h2>
      
      {/* Desktop Table */}
      <div className="hidden md:block bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
         <table className="w-full text-left text-sm text-slate-400">
            <thead className="bg-slate-950/50 text-slate-200 font-medium uppercase text-xs">
                <tr>
                    <th className="px-6 py-4">Report Name</th>
                    <th className="px-6 py-4">Date</th>
                    <th className="px-6 py-4">Generated By</th>
                    <th className="px-6 py-4">Status</th>
                </tr>
            </thead>
            <tbody className="divide-y divide-slate-800">
                <tr className="hover:bg-slate-800/50 transition-colors">
                    <td className="px-6 py-4 text-white">Portfolio Compliance Summary</td>
                    <td className="px-6 py-4">Jan 10, 2026</td>
                    <td className="px-6 py-4">Admin User</td>
                    <td className="px-6 py-4"><span className="text-emerald-400">Completed</span></td>
                </tr>
                <tr className="hover:bg-slate-800/50 transition-colors">
                    <td className="px-6 py-4 text-white">Risk Assessment Matrix</td>
                    <td className="px-6 py-4">Jan 8, 2026</td>
                    <td className="px-6 py-4">Admin User</td>
                    <td className="px-6 py-4"><span className="text-emerald-400">Completed</span></td>
                </tr>
            </tbody>
         </table>
      </div>

      {/* Mobile Card View */}
      <div className="md:hidden space-y-3">
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
          <div className="flex justify-between items-start mb-2">
            <span className="text-white font-medium">Portfolio Compliance Summary</span>
            <span className="text-emerald-400 text-xs">Completed</span>
          </div>
          <div className="text-xs text-slate-500">Jan 10, 2026 • Admin User</div>
        </div>
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
          <div className="flex justify-between items-start mb-2">
            <span className="text-white font-medium">Risk Assessment Matrix</span>
            <span className="text-emerald-400 text-xs">Completed</span>
          </div>
          <div className="text-xs text-slate-500">Jan 8, 2026 • Admin User</div>
        </div>
      </div>

      {/* Success Modal */}
      <AnimatePresence>
        {showSuccessModal && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowSuccessModal(false)}
              className="absolute inset-0 bg-black/70 backdrop-blur-sm"
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative w-full max-w-md bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl overflow-hidden"
            >
              <div className="p-6 text-center">
                <div className="w-16 h-16 bg-emerald-500/10 rounded-full flex items-center justify-center mx-auto mb-4">
                  <CheckCircle className="w-8 h-8 text-emerald-400" />
                </div>
                <h3 className="text-xl font-bold text-white mb-2">Report Downloaded!</h3>
                <p className="text-slate-400 mb-6">
                  <span className="text-white font-medium">{downloadedReport}</span> has been generated and downloaded successfully.
                </p>
                <button
                  onClick={() => setShowSuccessModal(false)}
                  className="w-full py-3 bg-emerald-500 hover:bg-emerald-400 text-slate-900 font-bold rounded-lg transition-colors"
                >
                  Done
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Click outside to close dropdowns */}
      {(showDateDropdown || showFilterDropdown) && (
        <div 
          className="fixed inset-0 z-10" 
          onClick={() => { setShowDateDropdown(false); setShowFilterDropdown(false); }}
        />
      )}
    </div>
  );
};

export default ReportsView;
